config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users, only: [:new, :create]
  resources :registered_applications
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :username, length: { minimum: 1, maximum: 100 }, presence: true
  validates :password, presence: true, length: { minimum: 6 }, if: 'password_digest.nil?'
  validates :password, length: { minimum: 6 }, allow_blank: true
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 254 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  def index
    @registered_applications = RegisteredApplication.all
  end

  def show
    @registered_application = RegisteredApplication.find(parmas[:id])
  end

  def new
    @registered_application = RegisteredApplication.new
  end

  def create
    @registered_application = RegisteredApplication.new
    @registered_application.name = params[:registered_application][:name]
    @registered_application.url = params[:registered_application][:url]
    @registered_application.user = current_user
    if @registered_application.save
      redirect_to registered_applications_path, notice: 'Appplication was saved successfully.'
    else
      flash.now[:alert] = 'Error registering application. Please try again.'
      render :new
     end
  end

  def edit
    @registered_application = RegisteredApplication.find(parmas[:id])
    @registered_application.name = params[:registered_application][:name]
    @registered_application.url = params[:registered_application][:url]
  end

  def update
    @registered_application = RegisteredApplication.find(params[:id])
  end

  def destroy
    registered_application = RegisteredApplication.find(params[:id])
    registered_application.destroy
    if @registered_application.destroy
      redirect_to @registered_applications, notice: 'Appplication was deleted successfully.'
    else
      flash.now[:alert] = 'Error deleting application. Please try again.'
      redirect_to registered_applications_path, notice: 'Appplication was deleted successfully.'
     end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      create_session(user)
      flash[:notice] = "Welcome, #{user.username}!"
      redirect_to root_path
    else
      flash.now[:alert] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
    destroy_session(current_user)
    flash[:notice] = "You've been signed out, come back soon!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end


   def create
     @user = User.new
     @user.username = params[:user][:username]
     @user.email = params[:user][:email]
     @user.password = params[:user][:password]
     @user.password_confirmation = params[:user][:password_confirmation]

     if @user.save
       flash[:notice] = "Welcome #{@user.username}!"
       create_session(@user)
       redirect_to root_path
     else
       flash.now[:alert] = "There was an error creating your account. Please try again."
       render :new
     end
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def create_session(user)
    session[:user_id] = user.id
  end

  def destroy_session(user)
    session[:user_id] = nil
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmetrics</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <br>
  <div class="pull-right user-info">
    <% if current_user %>
    <%= current_user.username %>
    -
    <%= link_to "Sign Out", session_path(current_user), method: :delete %>
  <% else %>
    <%= link_to "Sign In", new_session_path %>
    or
    <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </div>
  <br>
  <body>

    <%= yield %>

  </body>
</html>

app/views/registered_applications/index.html.erb
<h1>Registered Applications</h1>

<div class="row">
  <div class="col-md-8">
    <% @registered_applications.each do |app| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= app.name %>
          <small>
            <%= link_to "Delete", [app.user, app], method: :delete %></small>
        </h4>
        <small> 
          <%= app.url %>
        </small>
      </div>
    </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "Register New Apllication", new_registered_application_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/registered_applications/new.html.erb
<h1>Register New Application</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for registering new applications:</p>
     <ul>
       <li>Include a name for the application</li>
       <li>Application must be a valid web address</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @registered_application do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter application name" %>
       </div>
       <div class="form-group">
         <%= f.label :url %>
         <%= f.text_area :url, class: 'form-control', placeholder: "Enter application url" %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/users/new.html.erb
<h2>Sign up</h2>

  <div class="row">
    <div class="col-md-8">
      <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
          <div class="alert alert-danger">
            <h4><%= pluralize(@user.errors.count, "error") %>.</h4>
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
  <% end %>

app/views/welcome/index.html.erb
<br>
 <div class="jumbotron">
   <h1>Blocmetrics</h1>
   <p>Bloccit is a resource for sharing links with your friends!</p>
   <p>
     <%= link_to "Sign In", new_session_path %> or
     <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %> today!
   </p>
 </div>

 <div class="row">
   <div class="col-md-4">
     <h2>Solves world hunger</h2>
     <p>Blocmetrics will deliver food and water to those in need, all over the world.</p>
   </div>
   <div class="col-md-4">
     <h2>Eliminates poverty</h2>
     <p>Blocmetrics will deliver money and education to those in need, all over the world.</p>
   </div>
   <div class="col-md-4">
     <h2>Makes you better looking</h2>
     <p>Blocmetrics will make you better looking: it's scientifically proven to make men look like Ryan Gosling and women look like Shakira.</p>
   </div>
 </div>